# base_global_planner:  "navfn/NavfnROS"
base_global_planner: "global_planner/GlobalPlanner"

NavfnRos:
  allow_unknown: false
  default_tolerance: 0.1



GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.1
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: true
  orientation_mode: 1
  orientation_window_size: 1
  outline_map: true 
