footprint: [[-0.1, 0.062], [0.1, 0.062], [0.1, -0.062], [-0.1, -0.062]]
footprint_padding: 0.02

robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.75


obstacle_range: 2.0
raytrace_range: 3.0


# layer defnition
static:
  enable: true
  map_topic: /map
  subscribe_to_updates: true

obstacles_layer:
  enable: true
  observation_sources: lidar_1
  lidar_1:
    {
      data_type: LaserScan,
      topic: /urr_bot/scan,
      marking: true,
      clearing: true,
    }


