global_costmap:
  global_frame: map
  rolling_window: false
  static_map: true
  
  inflation:
    enabled: true
    inflation_radius: 0.12

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}