local_costmap:
  global_frame: odom
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  static_map: false 

  inflation:
    enabled: true
    inflation_radius: 0.33 

  plugins:
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
